### ISSUE TITLE
файл или папка

### ISSUE THREAD

**Issue by kuzmichevdima** [korvin001/TextGenerator#10]
https://github.com/korvin001/TextGenerator/blob/1337dfb9b903225932a55bf36867d1eb80877b13/train.py#L56

Почему аргумент называется input_dir, но используется как название файла?

https://github.com/korvin001/TextGenerator/blob/1337dfb9b903225932a55bf36867d1eb80877b13/train.py#L42

**Comment by corwinnn** [comment]
@kuzmichevdima fixed
