### ISSUE TITLE
if else

### ISSUE THREAD

**Issue by kuzmichevdima** [korvin001/TextGenerator#14]
https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/generate.py#L38-L40

https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/generate.py#L41-L43

я не понимаю, зачем так писать. Кажется, что раз начальная инициализация не в ифе происходит, то переменная всегда и остается с таким значением. А на самом деле оно может при некотором условии поменяться далее. Лучше использовать if ... else для такой логики, тогда читающему код сразу понятно, что значения присваиваются в зависимости от какого-то условия

**Comment by corwinnn** [comment]
@kuzmichevdima fixed
