### ISSUE TITLE
symbols_in_line

### ISSUE THREAD

**Issue by kuzmichevdima** [korvin001/TextGenerator#5]
https://github.com/korvin001/TextGenerator/blob/4631a7b18c52c0fb4b21b043139145e9c0412a07/generate.py#L32

20-магическая константа? Константы нужно выносить и как-то называть по code style

**Comment by corwinnn** [comment]
fixed

**Comment by kuzmichevdima** [comment]
название не по code style

**Comment by kuzmichevdima** [comment]
на самом деле, лучше сделать это параметром generate с дефолтным значением, а не константой

**Comment by corwinnn** [comment]
fixed
