### ISSUE TITLE
хранение всего ответа

### ISSUE THREAD

**Issue by kuzmichevdima** [korvin001/TextGenerator#6]
https://github.com/korvin001/TextGenerator/blob/4631a7b18c52c0fb4b21b043139145e9c0412a07/generate.py#L31

Общее замечание к генератору текстов #2: не храните весь ответ, поскольку он может быть крайне длинным (вдруг пользователь хочет свою войну и мир сгенерить через ваш скрипт)

**Comment by corwinnn** [comment]
fixed

**Comment by kuzmichevdima** [comment]
https://github.com/korvin001/TextGenerator/blob/1e38f9e0985f42a5177825d27c3574ebb80c1849/generate.py#L49

не fixed

**Comment by corwinnn** [comment]
Когда строка заканчивается text обнуляется
