### ISSUE TITLE
документация

### ISSUE THREAD

**Issue by kuzmichevdima** [korvin001/TextGenerator#7]

**Comment by corwinnn** [comment]
fixed

**Comment by kuzmichevdima** [comment]
не fixed
https://github.com/korvin001/TextGenerator/blob/1e38f9e0985f42a5177825d27c3574ebb80c1849/train.py#L11-L15

здесь и в других местах, про аргументы надо написать, что они обозначают. А также, что возвращает функция

**Comment by corwinnn** [comment]
fixed
