### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [korvin001/TextGenerator#9]
https://github.com/korvin001/TextGenerator/blob/1337dfb9b903225932a55bf36867d1eb80877b13/generate.py#L16

https://github.com/korvin001/TextGenerator/blob/1337dfb9b903225932a55bf36867d1eb80877b13/train.py#L24

d. Что за словарь, непонятно по названию.

https://github.com/korvin001/TextGenerator/blob/1337dfb9b903225932a55bf36867d1eb80877b13/generate.py#L19

s_word

https://github.com/korvin001/TextGenerator/blob/1337dfb9b903225932a55bf36867d1eb80877b13/train.py#L36

как по названию given понять, что это название файла?

и так далее

**Comment by corwinnn** [comment]
@kuzmichevdima fixed

**Comment by kuzmichevdima** [comment]
https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/train.py#L33

название функции - прочитать из директории. Что прочитать? Почему эта функция еще и записывает модель, хотя по названию она только читает?

почему путь до файла с моделью называется model, ведь это не сама модель

документация неактуальна:
https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/train.py#L35-L37

смысл вот этих двух строк мне не ясен:
https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/train.py#L41
https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/train.py#L52

**Comment by kuzmichevdima** [comment]
https://github.com/korvin001/TextGenerator/blob/fade8bf05485962e357f220d88f52b2dd7338d7c/generate.py#L19
так и не исправлено

**Comment by corwinnn** [comment]
@kuzmichevdima fixed
